inventory_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include



urlpatterns = [
    path('', include('accounts.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('stock/',include('stock.urls')),
    path('menu/',include('menu.urls')),
    path('order/',include('orders.urls')),
  
    path('accounts/', include('django.contrib.auth.urls')),

    
]

menu/urls.py
from django.urls import path
from .views import menu
app_name='menu'
urlpatterns = [
    path('',menu,name='menu_views'),
]

stock/urls.py
from django.urls import path
from .views import add_stock, delete_stock, view_stock,edit_stock
app_name='stock'
urlpatterns = [
   path('view/',view_stock,name='stock_views'),
   path('add/',add_stock,name='add_stock'),
   path('edit/<int:id>/',edit_stock, name="edit_stock"),
   path('delete/<int:id>/',delete_stock, name="delete_stock"),
 
 
]
 

stock/models.py
from django.db import models

class Stock(models.Model):
   category=models.CharField(max_length=15)
   product=models.CharField(max_length=25)
   quantity=models.IntegerField()
   measurement=models.CharField(max_length=5)
   price_item=models.IntegerField()
   total_price=models.IntegerField()

# Create your models here.

stock/forms.py
from django import forms
from django.forms import fields
from django.forms.formsets import formset_factory
from .models import Stock
 
class AddStockForm(forms.ModelForm):
   class Meta:
       model=Stock
       fields="__all__"

stock/views.py
from django.http import request
from django.shortcuts import redirect, render
from .forms import AddStockForm
from .models import Stock

 
# Create your views here.
def stock(request):
   return render(request,'stock.html',{})
 
# def add_stock(request):
#     form=AddStockForm()
#     return render(request,"add_stock.html",{
#         "form":form,
#     })
def add_stock(request):
   if request.method=='POST':
       form=AddStockForm(request.POST,request.FILES)
       if form.is_valid():
           form.save()
       else:
           print(form.errors)
   else:
       form=AddStockForm()
   return render(request,"add_stock.html",{"form":form})
 
def view_stock(request):
   stock=Stock.objects.all()
   return render(request,"stock.html",{ 'stock':stock})
 
 
def edit_stock(request,id): 
   stock=Stock.objects.get(id=id)
   if request.method=="POST":
       form=AddStockForm(request.POST,request.FILES,instance=stock)
       if form.is_valid():
           form.save()      
   else:
       form=AddStockForm(instance=stock)
   return render(request,'edit_stock.html',{"form":form})
def delete_stock(request,id):
   stock=Stock.objects.get(id=id)
   stock.delete()
   return redirect(stock)

stock/templates/add_stock.html
{% include 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Add-stock-form</title>
</head>
<body>
   <div class="wrapper">
       <div class="form">
    <form method="POST" enctype="multipart/form-data">
        {%csrf_token%}
        <img src="https://akirachix.com/img/logo.png?_cchid=1660c557f83aa4644e2a8d4bf0ddd4fb">
        <h1>Add stock</h1>
        {{form.as_p}}
        <button>Submit</button>
    </form>
    </div>
    </div>
  
   <style>
 
       h1{
           text-align: center;
       }
         body{
             background-color:white;
             align-items: center;
             justify-content: center;
             font-size: 20px;
             color:purple;
         }
         input{
            width: 100%;
            outline: none;
            border: 1px solid ;
            font-size: 15px;
            padding: 8px 8px;
            border-radius: 20px;
        }
        select{
            width: 100%;
            padding: 8px 10px;
            border-radius: 3px;
            transition: all 0.3;
        }
        .wrapper{
       max-width: 500px;
       width: 80%;
       background: #fff;
       margin: 20px auto;
       padding: 30px;
       box-shadow: 1px 1px 2px rgba(0,0,0, 125);
        }
        .wrapper.form.inputfield{
            margin-bottom: 15px;
            display: flex;
            align-items: center;
        }
        .wrapper.wrapper.form.input_field label{
            width: 200px;
            color: black;
            margin-right: 10px;
            font-size: 14px;
        }
       button{
           top: 30px;
           height: 50px;
           width :50%;
           border-radius: 6px;
           align-items: center;
           font-size: 1.4rem;
       }
       .pic{
           background-size: contain;
           width: 80%;
           text-align: center;
           height: 150px;
       }
       button:hover{
           color: white;
           background-color: purple;
           cursor: pointer;
       }
        img{
           margin-left:50px;
           width:100px;
       }
 
   </style>
</body>
</html>

stock/templates/stock.html
{% include 'base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Document</title>
</head>
<body>
 
   <h1>Stock</h1>
<div class="stock">
   <table>
       <tr>
           <th>Category</th>
           <th>product</th>
           <th>Quantity</th>
           <th>Measurement</th>
           <th>Price per Item</th>
           <th>Total price</th>
           <th>Edit stock</th>
           <th>Delete</th>
       </tr>
 
       <tr>
           {% for stock in stocks %}
           <td>{{stock.category}}</td>
           <td>{{stock.product}}</td>
           <td>{{stock.quantity}}</td>
           <td>{{stock.measurement}}</td>
           <td>{{stock.price_item}}</td>
           <td>{{stock.total_price}}</td>
           <td><a href="{% url 'stock:edit_stock' id=stock.id%}">Edit</a></td>
           <td><a href="{% url 'stock:delete_stock' id=stock.id}">Delete</a></td>
       </tr>
       {% endfor %}
   </table>
</div>
   <style>
       h1{
            text-align: center;
        }
        .stock{
           margin-left: 190px;
           background-color:rgb(244, 240, 245);
      
        }
         table, td, th {
           border: 1px solid #ddd;
           text-align: left;
           padding-left: 48px;
        
         }
      
         tr:hover {
           background-color:rgb(244, 240, 245);
           cursor: pointer;
         }
         th, td {
           padding: 15px;
         }
         th{
           background-color: rgb(221, 168, 226);
      
         
           color: black;
         }
         img{
           height: 50px;
           width: 50px;
         }
    </style>
</body>
 
</html>