dashboard/urls.py
from django.urls import path
from .views import dashboard
app_name='dashboard'
urlpatterns = [
    path('dashboard/',dashboard,name='dashboard_views'),
]

inventory_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include



urlpatterns = [
    path('', include('accounts.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('admin/', admin.site.urls),
    path('stock/',include('stock.urls')),
    path('menu/',include('menu.urls')),
    path('order/',include('orders.urls')),
  
    path('accounts/', include('django.contrib.auth.urls')),

    
]

menu/urls.py
from django.urls import path
from .views import menu
app_name='menu'
urlpatterns = [
    path('',menu,name='menu_views'),
]

orders/urls.py
from django.urls import path
from .views import orders
app_name='orders'
urlpatterns = [
    path('',orders,name='order_views'),
]

stock/urls.py
from django.urls import path
from .views import add_stock, delete_stock, view_stock,edit_stock
app_name='stock'
urlpatterns = [
   path('view/',view_stock,name='stock_views'),
   path('add/',add_stock,name='add_stock'),
   path('edit/<int:id>/',edit_stock, name="edit_stock"),
   path('delete/<int:id>/',delete_stock, name="delete_stock"),
 
 
]
 

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render

# Create your views here.
def dashboard(request):
    return render(request,'dashboard.html')

dashboard/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>base</title>
</head>
<body>
    <ul class="mytop-nav">
        <li class=" nav-li"><a href="{% url 'dashboard:dashboard_views' %}">Dashboard</a></li>
        <li class=" nav-li"><a href="{% url 'stock:stock_views' %}">Stock</a></li>
        <li class=" nav-li"><a href="{% url 'menu:menu_views' %}">Menu</a></li>
        <li class=" nav-li"><a href="{% url 'orders:order_views' %}">Orders</a></li>
    
        
     </ul>
     <style>

    .mytop-nav{
        letter-spacing: none;
        margin: -8px;
        padding-left: 20px;
        width: 200px;
        height: 100%;
        background-color:#812990;
        position: fixed;
        list-style: none;
        margin-top: -21px;
           }

   .nav-li a{
        display: block;
        width: 150px;
        color:white;
        text-decoration: none;
        font-size: 20px;
        padding-bottom: -20px;
        margin-bottom: 20px;
        margin-top: 40px;
        padding: 12px 16px;
        
        
    }
    .nav-li a:hover{
        background-color: antiquewhite;
        color:black;
       
    } 
    .heading{
        margin-left: 400px;
        font-size: 70px;
        padding-top: 80px;
    }
</style>

</body>
</html>

dashboard/templates/dashboard.html
{% include 'base.html' %}
<!DOCTYPE html>
<html lang="en">
 
<head>
 <meta charset="UTF-8">
 <meta http-equiv="X-UA-Compatible" content="IE=edge">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Dashboard</title>
</head>
 
<body>
 <table>
 
   <div class="dashboard-table">
     <table>
       <h1>Dashboard</h1>
       <h2>Stock</h2>
 
 
       <div class="dropdown">
         <button class="dropbtn">Category</button>
         <div class="dropdown-content">
           <a href="# ">Dry goods</a>
           <a href="# ">Vegetables</a>
           <a href="# ">Meat</a>
           <a href="# ">Others</a>
         </div>
       </div>
 
 
 
 
       <tr>
         <th>Product</th>
         <th>Quantity</th>
       </tr>
 
       <tr>
         <td>Rice</td>
         <td>50kg</td>
       </tr>
       <tr>
         <td>Flour</td>
         <td>2bales</td>
       </tr>
       <tr>
         <td>Maize flour</td>
         <td>2bales</td>
       </tr>
     </table>
   </div>
   <style>
     .dropbtn {
       color: black;
       padding: 20px;
       font-size: 16px;
       border: none;
       border-radius: 20%;
 
     }
 
     .dropdown {
       position: relative;
       display: inline-block;
       padding-left: 55%;
     }
 
 
 
 
     .dropdown-content a {
       color: black;
       padding: 12px 16px;
       text-decoration: none;
       display: block;
     }
 
 
     .dropdown-content a:hover {
       background-color: white;
     }
 
     .dropdown:hover .dropdown-content {
       display: block;
      
     }
 
    
     .dropdown-content {
       display: none;
       position: absolute;
       background-color: rgb(158, 129, 158);
       min-width: 160px;
       z-index: 1;
      
      
     }
 
 
     table,
     td,
     th {
       border: 1px solid #ddd;
       text-align: left;
       border-collapse: collapse;
       border: 1px solid black;
       margin: 20px;
       margin-left: 20%;
     }
 
     th,
     td {
       padding: 25px;
       width: 430px;
 
     }
 
     th {
       background-color: white;
 
       color: black;
     }
 
     tr:hover {
       background-color: white;
       cursor: pointer;
     }
 
     img {
       height: 50px;
       width: 50px;
     }
 
     h1 {
       padding-left: 52%;
      
     }
     h2{
       padding-left: 56%;
       
     }
   </style>
</body>
 
</html>